### ISSUE TITLE
Sorting ChangeTrackingCollection...

### ISSUE THREAD

**Issue by blewis1975** [TrackableEntities/trackable-entities#101]
Is there an easy way to sort the items in a ChangeTrackingCollection without having to instantiate a new ChangeTrackingCollection? I’m using dynamic linq to sort the list with a string value using the code below. However, if I’ve already deleted an entity in the list, when I instantiate the new list, that deletion is lost. I would like to sort the list using a string value without having to instantiate a new list. Is there an easy way to do this?

string sortedBy = "Name asc, Description desc";

ChangeTrackingCollection sortedEntities = entities;
if (!string.IsNullOrEmpty(sortedBy))
{
IQueryable queryable = entities.AsQueryable();
IQueryable sortedList = queryable.OrderBy(sortedBy);
sortedEntities = new ChangeTrackingCollection(sortedList);
}

return sortedEntities;

**Comment by tonysneed** [comment]
To answer this I need a bit more info about your scenario with using dynamic linq.  What's the reason why you would need to create a new collection vs using an existing collection? Sorting a collection with System.Linq does not require the creation of a new collection.

**Comment by blewis1975** [comment]
I've provided the entire function that I'm using below. You can see this is a generic function where I don't know the specific type of entity collection that I'm sorting. The GetGridSortedBy() function returns an order by string that I'm using to sort using dynamic linq. Since I don't know the type of entity and don't want to hard code expressions in the OrderBy() function, I decided to use dynamic linq. I don't want to create a new ChangeTrackingCollection, but I don't know of a way to use the OrderBy() function and have the original collection sorted. Using the Queryable object was the only way I could get the list sorted, but I then had to instantiate another collection and pass that in. I would love to be able to call Sort() on the ChangeTrackingCollection and pass in a string and have the collection sorted. Is this possible or can you think of another way I can generically sort the original list? 

        public ChangeTrackingCollection<B> SortData<B>(ChangeTrackingCollection<B> entities, Type entityType) where B : EntityBase
        {
            // Retrieve the sorted by string.
            string sortedBy = View.GetGridSortedBy(entityType);
            
            ChangeTrackingCollection<B> sortedEntities = entities;
            if (!string.IsNullOrEmpty(sortedBy))
            {
                // Get the queryable object and sort it.
                IQueryable<B> queryable = entities.AsQueryable();
                IQueryable<B> sortedList = queryable.OrderBy(sortedBy);

                // Instantiate a new collection using the sorted list.
                sortedEntities = new ChangeTrackingCollection<B>(sortedList);
            }

            return sortedEntities;
        }

**Comment by tonysneed** [comment]
It looks like you just have to execute the query to get the items to sort.  You can do that either by using a `foreach` loop to iterate over the sorted IQueryable, or you can simply call `ToList()` to get a list of sorted items, as shown below. There is no need to create a new `ChangeTrackingCollection`.  For example:

```csharp
[Fact]
public void Can_sort_ChangeTrackingCollection_using_dynamic_linq()
{
    // Arrange
    var product1 = new Product {Id = 1, ProductName = "Espresso"};
    var product2 = new Product { Id = 1, ProductName = "Chai" };
    var changeTracker = new ChangeTrackingCollection<Product>(product1, product2);
    var queryable = changeTracker.AsQueryable().OrderBy("ProductName asc");

    // Act
    var sortedEntities = queryable.ToList();

    // Assert
    Assert.Equal("Chai", sortedEntities.ElementAt(0).ProductName);
    Assert.Equal("Espresso", sortedEntities.ElementAt(1).ProductName);
}
```

You have to think of the query and list as simply another view of the same objects contained in the`ChangeTrackingCollection`, which remains unchanged, including cached deletes.  Those entities live on the .NET heap and are simply referenced by each of the collections.

I created a GitHub repo with a project that contains a unit test for sorting items in a `ChangeTrackingCollection` using dynamic linq: [tonysneed/Demo.SortedTrackingCollection](https://github.com/tonysneed/Demo.SortedTrackingCollection).  I hope this helps.

**Comment by blewis1975** [comment]
Thanks for your quick response. I'm probably not being clear in what I'm trying to do. The function that I need is one that takes a ChangeTrackingCollection, sorts the collection using a string, and returns a ChangeTrackingCollection. The only solution I found was one where I had to create a new ChangeTrackingCollection, but then I lose any deletions I've already done in that list. 

In your code above, changeTracker.AsQueryable().OrderBy("ProductName asc") doesn't sort the data in the changeTracker object, however, I still need to get back to a ChangeTrackingCollection. Make sense or am I missing something? Again, thanks for your help.

**Comment by tonysneed** [comment]
Your question relates to a common problem of binding to a collection which you want to sort, but which does not internally support sorting, filtering, etc, for example, an `ObservableCollection`.  `ChangeTrackingCollection` is one such collection.  It extends `ObservableCollection` and adds change tracking, but like `ObservableCollection` it does not let you sort the items, etc.

There are two basic ways to solve the problem.  One is to bind to a view of the collection, for example a `CollectionViewSource`, rather than to the collection itself.  You would still store the `ChangeTrackingCollection` in your view or view model (and use it for persisting changes to a service), but your view would bind to the `CollectionViewSource`.  For an example, check out [this tutorial](http://www.blackwasp.co.uk/WPFCollectionViewsFiltering.aspx), then substitute `ObservableCollection` for `ChangeTrackingCollection`.

Another approach would be to *extend* `ChangeTrackingCollection` and add methods for sorting, filtering, etc.  This would allow you to bind directly to the `ChangeTrackingCollection` instead of using a `CollectionViewSource` and would be relevant to non-UI scenarios.  See [this article](http://www.mesta-automation.com/how-to-make-a-sortable-observablecollection-c/) for an example of this approach.  If you choose this route, you could create a `SortedChangeTrackingCollection` that extends `ChangeTrackingCollection` and adds a `Sort` method that accepts a `string`.  Then you would use dynamic linq in that method to sort the items in the `ChangeTrackingCollection`.  I hope this helps!

**Comment by blewis1975** [comment]
Thanks Tony! Instead of extending the ChangeTrackerCollection class, I just created an extension method to handle the sorting. I've provided it below, in case somebody else needs it in the future. Thanks again for your help!

        public static void Sort<TEntity>(this ChangeTrackingCollection<TEntity> list, string orderBy) where TEntity : class, TrackableEntities.ITrackable, INotifyPropertyChanged
        {
            // Sort the collection to get a sorted list.
            List<TEntity> sortedItemsList = list.AsQueryable().OrderBy(orderBy).ToList();

            // Loop through the sorted list and move the item to the sorted index in this collection.
            foreach (TEntity item in sortedItemsList)
            {
                list.Move(list.IndexOf(item), sortedItemsList.IndexOf(item));
            }
        }

**Comment by tonysneed** [comment]
Glad I could help!
