### ISSUE TITLE
Exception when adding same entity to M-N relation

### ISSUE THREAD

**Issue by luboshl** [TrackableEntities/trackable-entities#102]
Hi Tony,

I probably found an issue when I add one enitity twice to two other entities when relation is defined as M-N.

Model looks like this:
![image](https://cloud.githubusercontent.com/assets/4955190/12221532/f2a7a51e-b79e-11e5-9386-484a159b8073.png)

I have these clasees:
```c#
[Table("Triggers")]
public class SimpleTrigger : EntityBase
{
  public string SimpleTriggerProperty { get; set; }

  // reference only due to M-N relation
  public ICollection<Task> Tasks { get; set; }
}

[Table("Actions")]
public class SimpleAction : EntityBase
{
  public int SimpleActionProperty { get; set; }

  // reference only due to M-N relation
  public ICollection<Task> Tasks { get; set; }
}

[Table("Tasks")]
public class Task : EntityBase
{
  public ICollection<SimpleTrigger> Triggers { get; set; }
  public ICollection<SimpleAction> Actions { get; set; }

  public Task()
  {
    this.Triggers = new List<SimpleTrigger>();
    this.Actions = new List<SimpleAction>();
  }
}
```
Then I create instances of entities:
```c#
var simpleTrigger = new SimpleTrigger { Name = "Trigger 1", SimpleTriggerProperty = "Value 1" }
var simpleAction = new SimpleAction { Name = "Action 1", SimpleActionProperty = 1 };
var task1 = new Task { Name = "Task 1" };
var task2 = new Task { Name = "Task 1" };

// add trigger and action to task1
task1.Triggers.Add(simpleTrigger);
task1.Actions.Add(simpleAction);

// add THE SAME trigger and THE SAME action to task2
task2.Triggers.Add(simpleTrigger);
task2.Actions.Add(simpleAction);

using (var ctx = new EfSampleDbContext())
{
  foreach (var trigger in triggers)
    trigger.TrackingState = TrackingState.Added;

  foreach (var action in actions)
    action.TrackingState = TrackingState.Added;

  foreach (var task in tasks)
    task.TrackingState = TrackingState.Added;

  ctx.ApplyChanges(triggers);
  ctx.ApplyChanges(actions);
  ctx.ApplyChanges(tasks);

  ctx.SaveChanges();

  // !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  // The last statement throws this excpetion:
  //
  // System.Data.Entity.Infrastructure.DbUpdateException: An error occurred while saving entities that do not expose foreign key properties
  // for their relationships. The EntityEntries property will return null because a single entity cannot be identified as the source
  // of the exception. Handling of exceptions while saving can be made easier by exposing foreign key properties in your entity types.
  // See the InnerException for details. ---> System.Data.Entity.Core.UpdateException: An error occurred while updating the entries.
  // See the inner exception for details. ---> System.Data.SqlClient.SqlException: The INSERT statement conflicted with the FOREIGN KEY
  // constraint "FK_dbo.TaskActions_dbo.Tasks_Task_Id". The conflict occurred in database "EfSample", table "dbo.Tasks", column 'Id'.
  // The statement has been terminated.
  // ...
}
```

Full VS solution with sample:
[EF_MN_Sample.zip](https://github.com/TrackableEntities/trackable-entities/files/84089/EF_MN_Sample.zip)

Sample uses three strategies:
1) Add entities to context's DbSets explicitly by method Add() - this works fine.
2) Add entities with TrackableEntities with TrackingState set to "Add" - throw an exception above.
3) Add entities with TrackableEntities without TrackingState - throw another exception when calling ctx.ApplyChanges(tasks);

Am I doing something wrong? How to add entities with M-N references in the example above using TrackableEntities?

Best wishes
Lubos

**Comment by tonysneed** [comment]
Hello @luboshl,

Thanks for submitting the issue.  I will have a look at your sample to see why the error might be occurring.  I think all you need to do is call `ctx.ApplyChanges(tasks)`, which should walk down to mark all related entities as added, so passing `triggers` and `actions` to `ApplyChanges` should not be necessary.  However, I'll set up some tests to make sure that all entities are marked as Added when `ApplyChanges` is called, and that it matches the behavior of calling `Add` on the `DbSet`.

Cheers,
Tony

**Comment by tonysneed** [comment]
I see now why your update was failing.  It has to do with the nature of **many-to-many-relations**.  This is documented in the **TrackableEntities.EF.6.Tests.NorthwindDbContextTests**: `Apply_Changes_Should_Mark_Added_Employee_As_Added_And_Added_Territories_As_Unchanged`, where you'll see the following comment:

```csharp
// NOTE: Because parent is added, added children will be marked as unchanged
// but added to the M-M relation
``` 

The reason for this behavior is that, with M-M relations, there is no way to tell whether the entity you are adding already exists and is simply to be added to the relationship with the parent entity, or if the entity does not exist and you wish to create the related entity and then add it to the relation.  So TE is conservative in this regard and assumes that you are adding an existing entity to the relationship, unless you indicate otherwise.

The way you indicate that the entity is supposed to be **created** and **added to the M-M relation** is to *explicitly* mark entities on the other side of the M-M relation as `Added`.  In your case, it is simply a matter of calling `ApplyChanges` first on `tasks`, then calling `ApplyChanges` on `triggers` and `actions`.  This will result in setting `EntityState` to `Added` for all the entities being created.

```csharp
// Applying changes to tasks comes first if triggers and actions to be created
ctx.ApplyChanges(tasks); // Will mark tasks as added, but mark triggers and actions as unchanged
ctx.ApplyChanges(triggers); // Explicitly mark triggers as added
ctx.ApplyChanges(actions); // Explicvitly mark actions as added
```

Let me know if this helps and it all makes sense. :smile:

**Comment by luboshl** [comment]
Hi Tony,

excellent, you are absolutly right! :+1: Your solution worked - **first** call `ApplyChanges` to `task` and **then** to `triggers` and `actions`. And I understand to your explanation :smile:

Thanks a lot!

**Comment by luboshl** [comment]
Hi @tonysneed,

unfortunately I found another problem :confused: Adding M-N referenced entities, all *added*, works (in my example), when there are **two** `task` instances with **one** instance of `trigger` and **one** instance of `action`. But when I try to add **two different** `triggers` and/or **two different** `actions` to **only one** `task`, it fails:

```c#
var task1 = new Task { Name = "Task 1", TrackingState = TrackingState.Added };
var trigger1 = new SimpleTrigger { Name = "Trigger 1", SimpleTriggerProperty = "Value 1", TrackingState = TrackingState.Added };
var trigger2 = new SimpleTrigger { Name = "Trigger 2", SimpleTriggerProperty = "Value 2", TrackingState = TrackingState.Added };

using (var ctx = new EfSampleDbContext())
{
  ctx.ApplyChanges(tasks); // <--- THIS FAILS ****************************
  ctx.ApplyChanges(triggers);
  ctx.ApplyChanges(actions);

  ctx.SaveChanges();
}
```

This is the exception:

```
System.InvalidOperationException: Saving or accepting changes failed because more than one entity of type 'EfSample.Entities.SimpleTrigger' have the same primary key value. Ensure that explicitly set primary key values are unique. Ensure that database-generated primary keys are configured correctly in the database and in the Entity Framework model. Use the Entity Designer for Database First/Model First configuration. Use the 'HasDatabaseGeneratedOption"fluent API or 'DatabaseGeneratedAttribute' for Code First configuration.
   at System.Data.Entity.Core.Objects.ObjectStateManager.FixupKey(EntityEntry entry)
   at System.Data.Entity.Core.Objects.EntityEntry.AcceptChanges()
   at System.Data.Entity.Core.Objects.EntityEntry.ChangeObjectState(EntityState requestedState)
   at System.Data.Entity.Core.Objects.EntityEntry.ChangeState(EntityState state)
   at System.Data.Entity.Internal.StateEntryAdapter.ChangeState(EntityState state)
   at System.Data.Entity.Internal.InternalEntityEntry.set_State(EntityState value)
   at TrackableEntities.EF6.DbContextExtensions.ApplyChanges(DbContext context, ITrackable item, ITrackable parent, ObjectVisitationHelper visitationHelper, String propertyName, Nullable`1 state)
   at TrackableEntities.EF6.DbContextExtensions.ApplyChangesOnCollectionProperties(TrackingState stateFilter, Boolean includeState, EntityNavigationProperty navProp, EntityCollectionProperty`1 colProp, DbContext context, ITrackable item, ObjectVisitationHelper visitationHelper, Nullable`1 state)
   at TrackableEntities.EF6.DbContextExtensions.ApplyChangesOnProperties(DbContext context, ITrackable item, ObjectVisitationHelper visitationHelper, Nullable`1 state)
   at TrackableEntities.EF6.DbContextExtensions.ApplyChanges(DbContext context, ITrackable item, ITrackable parent, ObjectVisitationHelper visitationHelper, String propertyName, Nullable`1 state)
   at TrackableEntities.EF6.DbContextExtensions.ApplyChanges(DbContext context, IEnumerable`1 items)
   at EfSample.Program.AddItemsWithTrackableEntitiesWithTrackingState(ICollection`1 triggers, IList`1 actions, IList`1 tasks) in D:\Visual Studio Projects\_Pokusy\EF_MN_Sample\EF_MN_Sample\Program.cs:line 111
   at EfSample.Program.CreateEntities(SampleStrategy strategy) in D:\Visual Studio Projects\_Pokusy\EF_MN_Sample\EF_MN_Sample\Program.cs:line 89
   at EfSample.Program.Main(String[] args) in D:\Visual Studio Projects\_Pokusy\EF_MN_Sample\EF_MN_Sample\Program.cs:line 37
```
I hope a haven't missed anything... Shall I add updated complete solution with the sample?

Best wishes
Lubos

**Comment by luboshl** [comment]
Aha, I investigated a little more and I found the differences:

## 1. Two `tasks`, one `trigger`
#### 1.1 `SimpleTrigger` **without** initialized `Tasks` collection - succeeds:
```c#
public class SimpleTrigger : EntityBase
{
  // reference only due to M-N relation
  public ICollection<Task> Tasks { get; set; }

  // no constructor initializing this.Tasks   <=============
}

task1.Triggers.Add(trigger1);
task2.Triggers.Add(trigger1);

ctx.ApplyChanges(tasks);
ctx.ApplyChanges(triggers);
```
#### 1.2 `SimpleTrigger` **with** initialized `Tasks` collection - fails:
```c#
public class SimpleTrigger : EntityBase
{
  // reference only due to M-N relation
  public ICollection<Task> Tasks { get; set; }

  public SimpleTrigger()
  {
    this.Tasks = new List<Task>();  //<============= initialized collection
  }
}

// this two rows
task1.Triggers.Add(trigger1);
task2.Triggers.Add(trigger1);

// or next two rows - with the same result
//trigger1.Tasks.Add(task1);
//trigger1.Tasks.Add(task2);

ctx.ApplyChanges(tasks);
ctx.ApplyChanges(triggers);   //<============= this fails
```
Message in the exception: `... Saving or accepting changes failed because more than one entity of type 'EfSample.Entities.Task' have the same primary key value. ...`

## 2. One `task`, two `triggers`
Here I started to prepare examples opposite to 1., but it is the same, except switching `task` to `trigger` and vice versa. What is important, it is then necessary to call `AplyChanges` to `triggers` first and then to `task` to get it working in the 2.1 *succeeded* example.

Error message for 2.2 would be: `... Saving or accepting changes failed because more than one entity of type 'EfSample.Entities.SimpleTrigger' have the same primary key value. ...`

## 3. Two `tasks`, two `triggers`
This is not possible at all, I think...

I hope my explanation is understandable...

Lubos

**Comment by tonysneed** [comment]
Hi @luboshl,

I'm glad I kept this issue open! :smile: EF will throw exceptions when it doesn't like the state of the entity when `SaveChanges` is called -- which I suppose is obvious. 🙄 But the error message indicates *why* EF isn't happy:

```
Saving or accepting changes failed because more than one entity of type have the same primary key value.
```

This error will occur when more than one entity is attached as `Unchanged` when instead it needs to be attached as `Added`, which is a side-effect of how the TE `ApplyChanges` method has to handle M-M relations.  The problem, as I first mentioned, is that there is no way to know whether an 'Added' entity already exists or needs to be created.

So the best answer is to clarify when it might be better for you to set the `EntityState` manually instead of calling `ApplyChanges`.  If you have M-M relations, if you have entities on one side of the relation which need to be created, rather than already existing, then rather than using `ApplyChanges`, you should instead call `DbSet.Add`, or `DbContext.Entry(entity).State = EntityState.Added`.  But this approach will fail if any of the entities already exist and are simply being added to the relationship, because EF will traverse the graph marking *all entities* as added, when existing ones need to be marked as `Unchanged.`  So in the case where you are added *existing* entities to a M-M relation, then calling `ApplyChanges` will succeed.

Now, this situation will improve with EF 7, which does not mark all downstream entities as `Added` but instead marks just the individual entity as `Added`.  This is a HUGE improvement over the behavior of EF6, which has been a pain to us developers for a very long time.  We are now working on a new version of TE for EF7 (it will be called TrackableEntities.Express), which takes advantage of the new graph behavior in EF7.  But EF7 will not reach RTM until April 2016, and even then it will not be feature complete -- and full support for M-M relations will still be missing at that time.  So we will be waiting for EF7 to mature more, but eventually we will have a full solution. :pray:

**Comment by luboshl** [comment]
Hi Tony,

thanks for quick response. Solution to use `DbSet.Add` is already working for me. But if I understand, it means, that unfortunately I cannot use TE for common scenario, where a graph of entities is created/modified/deleted and I want to save that through its root. I have to distinquish, whether I want to save entities with M-N relations, espetialy if they are created and added to the relation.

In my concrete solution I will create entities separately from creating references between them. I found the problem when I prepared some example data and I created them all in one step.

To the future, my idea was to have one `Save` method, then call `ApplyChanges`, let TE do the job and to be happy :laughing: I hope this will be able with EF 7 and I am looking forward to TrackableEntities.Express.

You've made great job with TE! :+1: 

Lubos

**Comment by tonysneed** [comment]
Note that you're **not** going to be able to use EF's `DbSet.Add` on M-M entities where you have an *existing* entity that you wish to relate to another entity in an M-M relation -- unless you resort to using the `ObjectContext` API from EF, which is painful because it requires you to specify hard coded aspects of your conceptual model.  TE does this nasty business under the covers, so you don't have to do it yourself. :smile: 

So even if you don't use TE, you will still need to distinguish between entities in M-M relations which *do exist* from those which *do not exist* and must be created.  So using TE would still be helpful, and it also handles the other kinds of relations (1-1, 1-M, M-1) without requiring customizations.

What I would suggest is writing a method that simply looks at your `Id` property and calls `DbSet.Add` if it is zero, or `DbSet.ApplyChanges` if it is non-zero.  That should solve the problem. :relieved:

Another idea would be to implement an overload of `ApplyChanges` which accepts a lambda expression where you could supply a condition for marking an entity as `Added`, then you would be able to supply as an argument: `e => e.Id == 0`.  The trick there would be to provide a way to specify the `Id` property on `e`, which we could do by providing a generic type argument on the method, so you could specify an interface or base class, such as your `EntityBase`.  Let me see if I can work on that ...

**Comment by luboshl** [comment]
I am thinking about one other thing. What about to have another `TrackingState`? Current state `Added` means *entity is created* or *entity is added as a reference*. Is it possible to distinquish between them? When I create **new instance**, I could set state for example `Created`, when I **add item** to `ChangeTrackingCollection`, I would set current `Added`. This could be done automatically with TE.Client or set explicitly. Then `ApplyChanges` would know, what to do :smile: 

Does it make sense to you? I know, that it would be very big change, if it is possible at all... Or did I missed something?

**Comment by tonysneed** [comment]
This would be another opportunity for an extensibility hook, and it would be a good match for the hook in `ApplyChanges` which I [mentioned above](https://github.com/TrackableEntities/trackable-entities/issues/102#issuecomment-170888322).  The best approach might be to create an `ITrackableExtended<TPropertyType>` interface which inherits from `ITrackable` and has an `TrackgingStateExtended` property of type `<TPropertyType>`.  You could use that for specifying additional property state info, such as your proposed `Created` state.  That would make it a lot easier for when you would call `ApplyChanges` on the server side using an overload which accepts a lambda expression or function pointer, so that it could remain decoupled from whatever logic is required to determine that the entity is to be created or not.

Let me know if this sounds alright, and I'll create a separate issue for the proposed enhancement.

**Comment by luboshl** [comment]
Yes, it sound understandable. So I will have to configure the solution to be able to run all test. Is that described somewhere? I noticed there is SQL Express used while I have LocalDB for example.

So I think you can create a sepparte issue as you wrote and you can finally close this issue :smile:

**Comment by tonysneed** [comment]
Unit tests are easy because they use xUnit from NuGet, so just build to restore packages. Then use VS Test Explorer or ReSharper to run the unit tests.

There are a few acceptance tests, and they use the VS Extension called SpecFlow, and there is a read me file in the project for configuring netsh.

**Comment by luboshl** [comment]
I already found documentation where everything is descirbed including coding standards :smile: I creted the Pull Request #104, because I use LocalDB and I need a little different configuration. I think someone other should also need this.

**Comment by tonysneed** [comment]
Ah yes I saw your PR right after replying. :) I'll be happy to accept it.

Would you possibly be interested in contributing to the extensions we discussed? I think the common extension would be a nice way to get involved, because it should be relatively straightforward to implement. I could create the starter VS project for you.

**Comment by tonysneed** [comment]
FYI, this is the best write up I've found on the whole process of submitting pull requests: http://blogs.msdn.com/b/cdndevs/archive/2016/01/06/submitting-your-first-pull-request.aspx

**Comment by luboshl** [comment]
Yes, I can try to prepare the extensions we discussed. It would be good if you prepare a VS project, because you have the vision about the name, structure and so on :+1:

**Comment by luboshl** [comment]
Or if you tell me your ideas, I can prepare the project. Shall I name it `TrackableEntities.Extensions`? I can see how you are using versioning, signing with a key. So I will create my branch for that and send pull request, where you can see if it meets your ideas.

**Comment by tonysneed** [comment]
Let me create that project first today. I will let you know as soon as it's pushed. Thanks!!!

**Comment by luboshl** [comment]
Yes, of course :smile:

**Comment by tonysneed** [comment]
Alright, I just pushed a commit with the new project, which you can pull down.  Then create a new local branch, in which you can add a public interface `ITrackableExtended<TProperty>` which inherits from `ITrackable`.

**Comment by tonysneed** [comment]
Closing this issue and creating new new issues for implementing the feature discussed here:

#105: ITrackableExtended<TProperty> interface

#106: DbContext.ApplyChanges overload accepting lambda
