### ISSUE TITLE
Repository queries in controller may conflict with TE

### ISSUE THREAD

**Issue by HDB2000** [TrackableEntities/trackable-entities#124]
We have found Trackable Entities very useful in our current project.  We are using it with Web API.

Sometimes we have wanted to use the Repository class as a general-purpose repository in a controller action and run into trouble.  

In one case, we were getting a row update from the client, but wanted to validate it by querying the same row (and others) from the table.  The update was failing.  We figured out that the query was pulling tracked records into our DbContext, and the detached record coming from the client could not be resolved against those records.  We found that adding .AsNoTracking to our query suppressed tracking, and allowed us to do our validation and update the database.

The next time, we wanted to clean up data in a table in a controller action, so we executed a query looking for invalid rows and tried to update them.  This also failed, but this time there was no detached record coming from the client.  The problem was that the Update method on the TE Repository class expects a detached entity and a DbContext with no tracked entities.  Our query was bringing back tracked records, and the Update call on each one was failing.  Once again, using .AsNoTracking on our query did the trick.

I'm trying to digest all of this.  As described on the project home page, TE is designed to "facilitate change-tracking across service boundaries", so it is understandable that TE assumes detached entities in the DbContext.  On the other hand, it doesn't seem unreasonable to want to do the operations I described above.

The easy conclusion is to use .AsNoTracking in every query we define in our repositories.  We are unlikely to ever want our DbContext to operate in attached mode.

It may also help new users to see .AsNoTracking used in the project sample code, or have the pitfall explained somewhere.

Many thanks for a great product!

**Comment by tonysneed** [comment]
@HDB2000,  Thanks for the feedback, and I'm grad you are finding TE useful.  As you mentioned, TE is designed for disconnected updates using entities passed to a Web API or WCF service.  So those entities should already be detached from any DbContext, and the `ApplyChanges` method attaches those entities to a DbContext, informing EF about pending inserts, updates and deletes in an object graph.  If those entities are already attached to the DbContext, then you will have conflicts, because EF makes assumptions about how the entity state needs to be painted.  If you need to query the database from within your service, `AsNoTracking` is your friend. :smile:

Thanks for the clarification, and I'll make a note to update the docs with this info.  Cheers!
