### ISSUE TITLE
GetChanges of EntityBase

### ISSUE THREAD

**Issue by w9n** [TrackableEntities/trackable-entities#151]
First of all, thanks for sharing again, this project is very instructive and helpfull (Looking forward to Core and ultra fast Docker Deployment :) )

Im still a beginner and wondering why there is no GetChanges() on EntityBase since ChangeTrackingCollection just iterates over the instances of ITrackable to get the changes. I think of a context where I update an EntityA from ViewModel(EntityA injected)  and dont have direct access to the according ChangeTrackingCollection of the injected instance.

**Comment by tonysneed** [comment]
@w9n The issue here is one of separation of concerns .. The entities need to be persistence ignorant and not aware of how changes are tracked.  Nevertheless, I can see what you're trying to accomplish, and this is the approach I would recommend:

In your ViewModel create a private `_changeTracker` member and initialize it in the ctor with the entities that has been injected.  You can then simply set `Tracking` to true to start change tracking and call `GetChanges` to get a clone of the entity with an object graph containing only changed items.

Let me know if this answers your question.

**Comment by w9n** [comment]
@tonysneed Oh I think I get it, this enables one to have multiple or none active "change-contexts" with different lifetimes on an Entity and only one or none active PropertyChanged listener through the visitationHelper implementation.

**Comment by tonysneed** [comment]
You got it!
