### ISSUE TITLE
NuGet package with symbols

### ISSUE THREAD

**Issue by weitzhandler** [TrackableEntities/trackable-entities#204]
Hi,

Reading the [docs](http://trackableentities.github.io/5-debugging.html) it appears dotPeek or another external tool is required to debug Trackable-Entities.

Would you consider including the [PDBs in a NuGet package](https://docs.microsoft.com/en-us/nuget/create-packages/symbol-packages) or downloadable elsewhere?

**Comment by tonysneed** [comment]
Check the NuGet/Packages folder and you'll see the symbols packages there for the latest version (2.5.6).

I also believe I published then to NuGet, so they should be in https://nuget.smbsrc.net.

**Comment by weitzhandler** [comment]
I added that website to VS' Symbol file locations list, and it still couldn't find the symbols:

![image](https://user-images.githubusercontent.com/2716316/32479793-31705cc0-c394-11e7-8de1-5ae697076787.png)

Result:

![image](https://user-images.githubusercontent.com/2716316/32479733-f0a01654-c393-11e7-8fd9-7dab8c19f016.png)

**Comment by tonysneed** [comment]
Hi Shimmy,

I'm not sure how well symbols source is working at symbolsource.org. (I can't even log in to see if it's there.)  I've found it to be flaky in the past, which is why I recommend dotPeek, which is free from JetBrains.

You may be able to install the symbols package locally however.  Let me give it a try.

**Comment by tonysneed** [comment]
I just uploaded the symbols packages for TE to NuGet (https://nuget.smbsrc.net), but it may take some time for them to become public.  When they do appear, you should be able to follow these instructions: https://www.symbolsource.org/Public/Wiki/Using.

That said, I think you'll have a better experience using dotPeek with these instructions: http://trackableentities.github.io/5-debugging.html.

**Comment by tonysneed** [comment]
Update: Looks like the symbols packages have posted.  I was able to get the debugging of source to work.  I'll post instructions here.  Also, we can possibly do a Skype session.

**Comment by tonysneed** [comment]
1. Go to Tools -> Options -> Debugger -> General.
2. Uncheck “Enable Just My Code (Managed only)”.
3. Uncheck “Enable .NET Framework source stepping”. Yes, it is misleading, but if you don't, then Visual Studio will ignore your custom server order (see further on) and only use it's own servers.
4. Check “Enable source server support”.
5. Uncheck “Require source files to exactly match the original version”
6. Go to Tools -> Options -> Debugger -> Symbols.
7. Select a folder for the local symbol/source cache. You may experience silent failures in getting symbols if it doesn't exist or is read-only for some reason.
8. Add symbol servers under “Symbol file (.pdb) locations”:
    - https://nuget.smbsrc.net

![vs-symbols](https://user-images.githubusercontent.com/2836367/32498621-cfef6250-c395-11e7-9d4d-73fa6cd53898.png)

**Comment by weitzhandler** [comment]
Thanks. I got the symbols working now!

**Comment by weitzhandler** [comment]
How does the symbols get updated in that symbol server? Is there a way to notify https://nuget.smbsrc.net that a new version is out?

**Comment by tonysneed** [comment]
There is a NuGet command I can execute to push the symbols packages, which by default will deploy to the NuGet symbol server.

The MyGet feed will publish NuGet packages whenever a commit is pushed to the develop branch.

**Comment by weitzhandler** [comment]
I've lost the MyGet feed address, can you please paste it in?

Looks like the same issue still exists in 2.5.6.1, or the assembly isn't the updated one (I believe this is what's happening).

**Comment by weitzhandler** [comment]
I find something weird, I added the new version to NuGet, cleaned the project and rebuilt, and apparently the assembly version points to the old one.
Could it be the assembly inside the NuGet package is the old one?

![image](https://user-images.githubusercontent.com/2716316/32694856-1a4bf914-c754-11e7-99e0-5fc40be625d5.png)

I just created a new console app, added TE via NuGet, after building the project, opening the bin folder shows that the assembly's version is 2.5.0.0, as in my own project (see pic below).

**Comment by tonysneed** [comment]
The assembly version I only increment when going to a new major number. It’s the package version you need to pay attention to.

**Comment by weitzhandler** [comment]
So the package version is the correct one, but it looks like my fix isn't there, nor can I use the symbols, I updated using the regular NuGet feed. Perhaps I should try the CI feed from MyGet, though I've lost its address.

**Comment by tonysneed** [comment]
I forgot to republish the symbols packages to NuGet after your fix was applied. It’s in the MyGet feed for sure, since CI is working again, but I’ll publish symbols to NuGet now, so the symbols for 2.5.6.1 will be there.

**Comment by tonysneed** [comment]
>So the package version is the correct one, but it looks like my fix isn't there.

Alright, I can see what's happening now.  It looks like I wrote a test that was supposed to fail, but didn't actually fail.  So I wasn't able to replicate your issue.  I'll re-open #197, and we can continue the discussion there.

**Comment by weitzhandler** [comment]
I installed the packages from the CI myget feed and I'm unable to find the symbols.
I tried the following addresses:
- http://myget.org/F/trackable-entities-ci/
- http://myget.org/F/trackable-entities-ci/symbol

**Comment by tonysneed** [comment]
I don’t remember if the symbols packages are published to MyGet. Are you still getting an exception with this package:

PM> Install-Package TrackableEntities.EF.6 -Version 2.5.6-CI00058 -Source https://www.myget.org/F/trackable-entities-ci/api/v3/index.json

**Comment by weitzhandler** [comment]
Although it would be handy being able to fiddle with the source, especially in the CI builds, looks like that exception is gone.

**Comment by tonysneed** [comment]
My build script does output symbols packages, but I’m not sure if those are published to MyGet. You would need to get the symbol server path correct. I’ll check it out.

**Comment by weitzhandler** [comment]
I'm following the instructions [here](http://docs.myget.org/docs/reference/symbols#Consuming_symbol_packages_in_Visual_Studio) and the symbols aren't loaded from the address https://www.myget.org/F/trackable-entities-ci/symbols.

Could be you're pushing the symbols to the wrong address? Maybe I need to be authenticated in order to access the CI symbols?

**Comment by tonysneed** [comment]
Yeah that’s not going to work since it’s secured. Can you give dotPeek a try? It’s free.

**Comment by weitzhandler** [comment]
- Dot peek won't give the exact code
- Can you debug properly with dotPeek?

**Comment by tonysneed** [comment]
It decompiles on the fly, so it should be accurate. I haven’t tried it recently, but it might be worth trying.

**Comment by tonysneed** [comment]
> Dot peek won't give the exact code. Can you debug properly with dotPeek?

Do the issue with VS finding source code is that it will grab it wherever it can find it.  You need to clear out the cache where it has previously stored source code.  For example, if you have the TE git repo cloned locally, VS may look for the source code there, which is not going to match the DLL because we use conditional compilation constants (for example, for EF6 vs EF5).

![source-step-mismatch](https://user-images.githubusercontent.com/2836367/32983396-7c438cd6-cc59-11e7-9bb3-e8bafc7fe1cf.png)

After I physically removed the TE project from my computer, then Visual Studio prompts for the source code location once you load the symbols from the PDB file, which is available if you are using the dotPeek symbol server (here are the [setup](https://www.jetbrains.com/help/decompiler/Using_product_as_a_Symbol_Server.html) instructions).

If VS is able to find the decompiled source code generated by dotPeek, the code will match perfectly, and you can then step through it.  When I tried it, I had to get ReSharper to decompile the source code, then VS was able to find it.

![source-step-match](https://user-images.githubusercontent.com/2836367/32983565-379ce322-cc5c-11e7-84cf-2c50021d784a.png)

So the best debugging experience is to use the symbols packages that I upload to NuGet when I've created a release and bumped the package version number.  But if you want to debug a CI release, then dotPeek / ReSharper is your best solution, since MyGet doesn't make the symbols packages generally available.

**Comment by weitzhandler** [comment]
I see.
Thank you so much for taking the time to investigate this!
