### ISSUE TITLE
ChangeTracker should have no deleted entities if entity is added and removed from changetracker

### ISSUE THREAD

**Issue by harrisunderwork** [TrackableEntities/trackable-entities#58]
Ran this testcase

https://github.com/tonysneed/trackable-entities/blob/develop/Source/Tests/TrackableEntities.Client.Tests/ChangeTrackingCollectionWithChildrenTests.cs#L648

If I put additional assert :

Assert.AreEqual(changeTracker._deletedEntities.Count, 0);

test case fails, reason for which I need _deletedEntities.Count == 0 is while applying changes, it restores it, which creates a wrong object graph.

To resolve this, I have moved this line :

https://github.com/tonysneed/trackable-entities/blob/develop/Source/TrackableEntities.Client/ChangeTrackingCollection.cs#L249 above https://github.com/tonysneed/trackable-entities/blob/develop/Source/TrackableEntities.Client/ChangeTrackingCollection.cs#L243.

Thoughts ?

**Comment by tonysneed** [comment]
It's a good point -- only deleted items should be cached.  If we're not marking the item as deleted, then it should remain uncached, because we're only interested in restoring deleted items, and we don't want items cached that shouldn't be, because they'd be serialized when they shouldn't be (with OnSerialzing/ed methods).

This is a perfect opportunity for you to create a pull request! :smile: What I suggest is linking back to this issue (have a look at the other PR's).  If you like, you can also include your fix.  But write the failing test first, because writing the fix.  Commit the failing test first, then create a second commit for the fix.  Sound good?

**Comment by harrisunderwork** [comment]
Which branch should I use to create pull request ?

Sorry if it sounds dumb question :)

**Comment by tonysneed** [comment]
No problema .. you'll be working locally at first .. create a new branch from dev and name it in a way that identifies the issue, for example: no-deleted-entities.  Then create your failing test there and commit it locally.  Then implement your fix and commit it locally.  Then push your commits to origin.

I like working with the [Git integration available with Visual Studio 2013](http://blogs.msdn.com/b/visualstudioalm/archive/2013/02/06/set-up-connect-and-publish-using-visual-studio-with-git.aspx).

After that you can go to GitHub and click a button to create a [pull request](https://help.github.com/articles/creating-a-pull-request).

**Comment by tonysneed** [comment]
Hello @harrisunderwork,

I'm checking back to see if this issue still needs to be resolved.  Are you basically saying that calling `GetChanges` after performing deletes restores the wrong object graph?

What would be most helpful is if you were to create a new unit test that demonstrates this behavior.  Or at the very least, paste sample code into a comment on this issue, so that I can see what is happening. (The links you posted are stale at this point, so I can't see the original lines of code you were referring to.)

Much thanks!
Tony

**Comment by harrisunderwork** [comment]
No problem, I will try to reproduce the issue.

Thanks.

**Comment by tonysneed** [comment]
@harrisunderwork, Any luck on a repro for this issue?  A failing test would be great, but you can also post a small example to a GitHub repro, which I can then fork.

**Comment by tonysneed** [comment]
Updating the label to **invalid** until we get a good repro.
